package br.com.gazintech.plugin.spring_utils.idempotency

import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.EnableAspectJAutoProxy
import org.springframework.data.redis.repository.configuration.EnableRedisRepositories

@EnableRedisRepositories
@EnableAspectJAutoProxy
@Configuration
class IdempotencyConfiguration